version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: chlgmlwn!00
      MYSQL_DATABASE: sqldb
    ports:
      - "3306:3306"
